version: '3.8'

services:
  database:
    image: postgres:13
    env_file:
      - ./backend/.env
    ports:
      - '5440:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: sh -c "npm run migrate && npm run dev"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - database
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend


volumes:
  postgres-data: